version: '{branch}-{build}'
image: Visual Studio 2017

init:
    - cmd: git config --global core.autocrlf true
    
install:
    - cmd: git submodule update --init --recursive
    - cmd: dotnet tool install --global dotnet-sonarscanner
    
before_build:
    - cmd: dotnet --version
    - cmd: dotnet restore --verbosity m
    - cmd: dotnet-sonarscanner begin /k:"CSF.ORM" /v:AppVeyor_build_%APPVEYOR_BUILD_NUMBER% /o:craigfowler-github /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=%SONARCLOUD_SECRET_KEY% /d:sonar.cs.nunit.reportsPaths=%APPVEYOR_BUILD_FOLDER%\Tests\TestResult.xml /d:sonar.cs.opencover.reportsPaths=%APPVEYOR_BUILD_FOLDER%\.CoverageReports\coverage.opencover.xml

build_script:
    - cmd: dotnet build

test_script:
    - cmd: mkdir .CoverageReports/
    - cmd: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=\"json,opencover\" /p:CoverletOutput=\"../../.CoverageReports/\" /p:MergeWith=\"../../.CoverageReports/coverage.json\"

after_test:
    - cmd: dotnet-sonarscanner end /d:"sonar.login=%SONARCLOUD_SECRET_KEY%"
