version: '{branch}-{build}'
image: Visual Studio 2017

init:
    - cmd: git config --global core.autocrlf true
    
install:
    - cmd: git submodule update --init --recursive
    - cmd: choco install sonarscanner-msbuild-netcoreapp30
    - cmd: nuget install -OutputDirectory %APPVEYOR_BUILD_FOLDER%\.OpenCover -Version 4.7.922 OpenCover
    - cmd: nuget install -OutputDirectory %APPVEYOR_BUILD_FOLDER%\.TestRunner -Version 3.7.0 NUnit.ConsoleRunner
    
before_build:
    - cmd: dotnet --version
    - cmd: dotnet restore --verbosity m
    - cmd: SonarScanner.MSBuild.exe begin /k:"CSF.ORM" /v:AppVeyor_build_%APPVEYOR_BUILD_NUMBER% /s:%APPVEYOR_BUILD_FOLDER%\.sonarqube-analysisproperties.xml /o:craigfowler-github /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=%SONARCLOUD_SECRET_KEY% /d:sonar.cs.nunit.reportsPaths=%APPVEYOR_BUILD_FOLDER%\Tests\TestResult.xml /d:sonar.cs.opencover.reportsPaths=%APPVEYOR_BUILD_FOLDER%\OpenCover.xml

build_script:
    - cmd: dotnet build

test_script:
    - cmd: .OpenCover\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:user -target:.TestRunner\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe -targetargs:"--result=%APPVEYOR_BUILD_FOLDER%\Tests\TestResult.xml Tests\CSF.Entities.Tests\bin\Debug\netcoreapp2.2\CSF.Entities.Tests.dll Tests\CSF.ORM.NHibernate4.Tests\bin\Debug\netcoreapp2.2\CSF.ORM.NHibernate4.Tests.dll Tests\CSF.ORM.Tests\bin\Debug\netcoreapp2.2\CSF.ORM.Tests.dll Tests\CSF.PersistenceTester.IntegrationTests\bin\Debug\netcoreapp2.2\CSF.PersistenceTester.IntegrationTests.dll Tests\CSF.PersistenceTester.Tests\bin\Debug\netcoreapp2.2\CSF.PersistenceTester.Tests.dll"  -output:%APPVEYOR_BUILD_FOLDER%\OpenCover.xml

after_test:
    - cmd: SonarScanner.MSBuild.exe end /d:"sonar.login=%SONARCLOUD_SECRET_KEY%"