version: '{branch}-{build}'
image: Visual Studio 2017

init:
    # Good practise, because Windows line endings are different from Unix/Linux ones
    - cmd: git config --global core.autocrlf true
    
before_build:
    - cmd: dotnet --version
    - cmd: dotnet restore --verbosity m

build_script:
    - cmd: dotnet publish


test_script:
    - dotnet test
