language: csharp
solution: CSF.ORM.sln

install:
  - nuget install NUnit.ConsoleRunner -Version 3.6.1 -OutputDirectory testrunner

script:
  - dotnet build
  - mono "./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe" Test.CSF.Data/bin/Debug/Test.CSF.Data.dll
